### PR TITLE
Server name support

### PR DESCRIPTION
**Pull request by fastlorenzo**
Added server name support for static servers. This is useful to reference servers by name, and a quick fix if you have multiple IPs per server (create multiple 'servers' in Ghostwriter, and assign them the same server name)

### CODE REVIEW

**Comment by covertgeek** [comment]
Referencing #6

**Comment by fastlorenzo** [comment]
Fixing #10 as well

**Comment by covertgeek** [comment]
@fastlorenzo -- I just wanted to let you know we aren't ignoring this pull request.  Since there are model changes, I'd like to work with Chris before accepting it.  

He's participating in the BlackHat conference this week and we'll pick it up next week.

**Comment by fastlorenzo** [comment]
@covertgeek no issues, I guessed you should be quite busy this week 👍 

On a side not, I have other ideas for the tool, I'll put that in an issue and see if I have time to work on that as well

**Comment by chrismaddalena** [comment]
Starting a review now that some of the big changes have ben merged. Only conflicts are some HTML files, so looks good so far. That was my biggest fear, that the PR would conflict with planned/in-progress updates.

**Comment by fastlorenzo** [comment]
@chrismaddalena should be fixed now

**Comment by fastlorenzo** [comment]
Added the support for transient servers as well, and fixed some layout issues.

**Comment by chrismaddalena** [comment]
@fastlorenzo This all looks great! Thank you for taking the work of getting everything ready to merge off of my plate, too. I just pulled the PR and ran some tests. Everything looks good and I really like the changes. This will be merged 😃

**Pull request merged**
