### PR TITLE
Allow registration for social accounts (SSO)

### PR DESCRIPTION
**Pull request by fastlorenzo**
### Requirements for Contributing a Bug Fix

* Fill out the template below. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* The pull request must only fix an existing bug. To contribute other changes, you must use a different template. You can see all templates at <https://github.com/atom/.github/tree/master/.github/PULL_REQUEST_TEMPLATE>.
* The pull request must update the test suite to demonstrate the changed functionality.
* After you create the pull request, all status checks must be pass before a maintainer reviews your contribution. For more details, please see <https://github.com/GhostManager/Ghostwriter/blob/master/CONTRIBUTING.md#submitting-a-pull-request>.

### Identify the Bug

#102 Social authentication requires registration to be opened, however the current implementation opens registration for username authentication as well.

#

### Description of the Change

1. Added a new environment setting to control registration when using social auth: `DJANGO_SOCIAL_ACCOUNT_ALLOW_REGISTRATION` (works the same way as the one for the username auth (`DJANGO_ACCOUNT_ALLOW_REGISTRATION`)
2. Fixed the visual layout of the login page to correctly display the Social Auth login buttons:

image

### Alternate Designs

Alternative would be to fully open registration on the platform, including with username/password, which is not an option for me.
Only allowing registration for Social Auth allows to grant access through the IDP (in my case, Azure AD, where the app is assigned to people that are allowed to access GhostWriter).

### Possible Drawbacks

N/A

### Verification Process

Tried various combination of enabling / disabling both types of registration (username / social auth) and validated the expected behavior.

### Release Notes

- Fixed Social Auth listing on login page
- Added env var to allow registration on social or username auth only

### CODE REVIEW

**Comment by chrismaddalena** [comment]
Thanks for submitting this, @fastlorenzo! I'll take a look at it as soon as I can. Updating authentication and registration is high on my TODO list to make ADFS integration easier. If this helps with that, even better.

**Comment by fastlorenzo** [comment]
@chrismaddalena did you already have time to review this one? I had a look at the Trello but didn't see anything about it.
It should be a minor change with no impact to current functionalities :eyes: 
PS: I see there is a minor merge conflict, I'll have a look and fix it.
Thanks!

**Comment by chrismaddalena** [comment]
The changes look fine. It will be necessary to add `DJANGO_SOCIAL_ACCOUNT_ALLOW_REGISTRATION` to Ghostwriter CLI, so it's in the DotEnv file without anyone having to edit it manually. Other variables may also need to be added.

@fastlorenzo What else did you do to make this work? This seems to cover everything:

1. Extend `INSTALLED_APPS` with at least one provider
2. Add `SOCIAL_AUTH_AUTHENTICATION_BACKENDS` for the provider(s)
3. Add `SOCIALACCOUNT_PROVIDERS` for the provider(s)
5. Change `ACCOUNT_AUTHENTICATION_METHOD` to `email` (possibly optional)

Some of that may always require editing the _base.py_ config file, but a lot of it could be handled by Ghostwriter CLI to make it easier.

**Comment by fastlorenzo** [comment]
@chrismaddalena I've made the changes listed in https://github.com/GhostManager/Ghostwriter/issues/102#issuecomment-883463006 to have it working with Azure AD (although this should be similar for other IDPs)

**Comment by chrismaddalena** [comment]
Thanks, that's what I needed to know. The other steps are unimportant for this PR. The changes here don't require the steps in #102 to be automated or simplified. That can come later to improve quality of life during setup and configuration.

**Pull request merged**
