### PR TITLE
Added customizable style for new paragraphs (*_rt) in docx templates

### PR DESCRIPTION
**Pull request by federicodotta**
Hello!

I inserted a customizable style for new docx paragraphs created by GhostWriter when the template contains one of the *_rt tags.

It is now possible to optionally add a style for new paragraph when a template is uploaded/modified. If the style filed is empty or None, the default value is used ("Normal" style).

I added the field in the model (and a migration with a default value), in the GhostWriter views/forms and in the admin panel. I hope I haven't forgotten any points.

At the moment the field in the view is displayed also for PPTX templates but it is used only for Word. If you prefer, we can add some JS code that show/hide the field when the right type of template is selected. At the moment I simply explained that the field is used only for Word templates.

This change should address the following issues:

- https://github.com/GhostManager/Ghostwriter/issues/278
- https://github.com/GhostManager/Ghostwriter/issues/296

I hope I modified all the related points and I have not introduced any bug. During my tests, my update seems to work correctly but this is the first time I updated this project and I may have made some mistakes.

Thank you for your great work!
Federico

### CODE REVIEW

**Comment by chrismaddalena** [comment]
Thanks for submitting this, @federicodotta! I'll test it out. This does help with the issues you linked. Some folks in those conversations want to be able to use more than one alternate paragraph style. This is all or nothing (uses the defined style or `Normal`), but it might be the closest solution. Everyone can still apply paragraph styles in the WYSIWYG editor.

**Comment by chrismaddalena** [comment]
Passing an argument to the `{{p }}` tags is an interesting idea. It would require forking `python-docx-tpl` and changing some code there, but it might work. I will look into that as a possible option for the future.

**Comment by federicodotta** [comment]
Hi @chrismaddalena! 

Another potential way that I was thinking about that does not require to modify the external python-docx-tpl project (but I'm not sure that it may be viable) is the following one.

We use a similar approach of the present pull request but we ask for a list of styles that the user want to use in his template (maybe comma separated o something else).

Then in reportwriter.py module we can add one attribute to the finding object for each style requested by the user, like in the following snippet of code:

```
for style in requested_styles:
    finding["impact_rt_" + style] = render_subdocument(
        finding["impact"], finding, self.report_queryset.docx_template.style
    )   
``` 

This way the user have to define a list of style he want to use in the Template page (as in the current pull request) but then he has all these styles available in his docx template and he can freely use one or another by changing the name of the attribute allover the document. Some examples are:

- impact_rt_customStyle
- impact_rt_Normal
- impact_rt (default to Normal)

What do you think on this approach. If you like it I can try to implement it (but I don't know precisely when :) )

Federico

**Comment by chrismaddalena** [comment]
@federicodotta Making it possible to use a list of styles might be helpful. This would work a little like CSS font settings. If `font1` is available, use it. If now, try `font2` and then `font3`.

**Comment by federicodotta** [comment]
@chrismaddalena I was thinking to make possible to the user to choose which style he wants to use in each tab. The purpose of the list defined in the template settings is only to allow us to create specific tags **for each inserted style**.

I try to be more clear. If the user in the list adds the two styles _custom_style_1_ and _custom_style_2_, instead of populating from GhostWriter only _finding["impact_rt"]_, we populate also _finding["impact_rt_custom_style_1"]_ and _finding["impact_rt_custom_style_1"]_.

This way the user can then call all these defined styles in his template docx as follows:

* {{p finding.impact_rt }}
* {{p finding.impact_rt_custom_style_1 }}
* {{p finding.impact_rt_custom_style_2 }}

What do you think about this approach? It seems to me that it can address all the issues and allows to choose styles in a granular way.

Thank you!

**Comment by federicodotta** [comment]
Hi @chrismaddalena,

Do you think that the way I described in the last reply to add customizable styles can be OK or you prefer a different approach?

If you like it I can try to implement it and then send another pull request.

Thank you!

Federico

**Comment by chrismaddalena** [comment]
Hey @federicodotta, I'm sorry. This PR slipped through the cracks while I had other things going on. I forgot to get back to you.

I think I like the second approach of offering the option to append a style name to a RichText object like `{{p finding.impact_rt_style1}}`, but there are a couple potential issues/questions.

First, what happens if the template does not have one of the requested styles? Do we allow that to cause a rendering error or fallback to the Normal style? Ghostwriter favors failing over proceeding with a default to avoid people thinking Ghostwriter produced a report incorrectly and seeing the fallback as a bug.

Does the feature support spaces, hyphens, or underscores? Style names can have spaces, so "Custom Style 1" might be represented as `{{p finding.impact.custom_style_1 }}`.

Style names will need to be consistently cased because they are case-sensitive. `Custom style 1` and `Custom Style 1` can be different styles. We can tell people they need to title case their style names like the existing style names, but I can see people reporting issues that an existing style isn't being found when they don't recognize the casing is an issue.

This means we'd need a strict naming scheme for style names.

The biggest issue is the report template linter. It uses an example of the report JSON containing every possible value. With this feature, we add RichText objects the linter does not know about. That will cause every template to fail linting.

While I like this approach, the best short-term option is your original submission that enables users to select one other paragraph style other than Normal to use.

**Comment by federicodotta** [comment]
Hi @chrismaddalena,

No problem for the delay. Excuse me for the double message but I'd rather have your opinion before start coding because I don't know in depth Ghostwriter code.

Thank you for your explanation. I agree with you. I leave the PR as is now.

Thank you!

Have a nice day,
Federico

**Comment by chrismaddalena** [comment]
No problem, @federicodotta. I've been busy and unable to get to this yet, but I will review everything again and then see about merging the PR. I consider everything in order and good to merge, but I want to ensure we have unit tests and documentation updates to accompany the changes.

**Pull request merged**
